USER_ID_HEADER = "X-User-Id"
ERROR_AUCTION_NOT_FOUND = "auction not found"
ERROR_FORBIDDEN = "forbidden"
ERROR_AUCTION_NOT_DRAFT = "auction is not a draft"
ERROR_STARTING_PRICE_POSITIVE = "starting_price_cents must be greater than 0"
ERROR_START_BEFORE_END = "start_time must be before end_time"

AUCTIONS_TABLE_NAME = "auctions"
AUCTION_ROUTER_PREFIX = "/auctions"

TITLE_MAX_LENGTH = 255

AUCTION_STATUS_DRAFT = "DRAFT"
AUCTION_STATUS_OPEN = "OPEN"
AUCTION_STATUS_UNSOLD = "UNSOLD"
AUCTION_STATUS_PAYMENT_PENDING = "PAYMENT_PENDING"
AUCTION_STATUS_SOLD = "SOLD"
AUCTION_STATUS_UNPAID = "UNPAID"

AUCTION_STATUSES = (
    AUCTION_STATUS_DRAFT,
    AUCTION_STATUS_OPEN,
    AUCTION_STATUS_UNSOLD,
    AUCTION_STATUS_PAYMENT_PENDING,
    AUCTION_STATUS_SOLD,
    AUCTION_STATUS_UNPAID,
)
